<< "ERROR -- caught exception: " << e.what() << endl;
	assert (false);
    }
}
